
services:
  api:
    build: .
    container_name: fintech_api
    env_file: .env
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy # Wait for db service to be healthy
    volumes:
      - .:/src


  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle_db
    env_file: .env
    ports:
      - "1522:1521"
    volumes:
      - fintech_data:/opt/oracle/oradata
    restart: unless-stopped
    healthcheck: # Add healthcheck to db service
      test: ["CMD", "sh", "-c", "sqlplus -L system/oracle@localhost:1521/XEPDB1 AS SYSDBA <<< 'select 1 from dual;' > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10 # Allow enough retries for Oracle to start

volumes:
  fintech_data: