"""Initial complete migration

Revision ID: 2950f69ad7c4
Revises: 
Create Date: 2026-02-20 14:28:25.332045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2950f69ad7c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aud_cartera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cartera', sa.Integer(), nullable=False),
    sa.Column('tipo_operacion', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('valor_anterior', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('valor_nuevo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('usuario_bd', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('id_tipo_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_cliente'], ['tipo_clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('precio_standar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria_producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_producto_id'], ['categoria_productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('proximo_vencimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_factura', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_pago', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('cartera_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cartera_id'], ['cartera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_num_factura'), 'facturas', ['num_factura'], unique=True)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('monto_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_index(op.f('ix_facturas_num_factura'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_table('cartera')
    op.drop_table('productos')
    op.drop_table('clientes')
    op.drop_table('tipo_clientes')
    op.drop_table('categoria_productos')
    op.drop_table('aud_cartera')
    # ### end Alembic commands ###
