"""migracion inicial de los modelos

Revision ID: 5c39e1eb977f
Revises: 
Create Date: 2026-02-09 18:38:45.792084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision: str = '5c39e1eb977f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('saldo_pendiente', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('proximo_vencimiento', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('precio_standar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cartera_id', sa.Integer(), nullable=False),
    sa.Column('categoria_producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cartera_id'], ['cartera.id'], ),
    sa.ForeignKeyConstraint(['categoria_producto_id'], ['categoria_productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('id_tipo_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_cliente'], ['tipo_clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_factura', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_pago', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('cartera_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cartera_id'], ['cartera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facturas_num_factura'), 'facturas', ['num_factura'], unique=True)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('monto_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('logmnr_i1cdef$'), table_name='logmnr_cdef$')
    op.drop_index(op.f('logmnr_i2cdef$'), table_name='logmnr_cdef$')
    op.drop_index(op.f('logmnr_i3cdef$'), table_name='logmnr_cdef$')
    op.drop_table('logmnr_cdef$')
    op.drop_index(op.f('logmnrc_i2seqgg'), table_name='logmnrc_seq_gg')
    op.drop_table('logmnrc_seq_gg')
    op.drop_table('logmnrc_gsii')
    op.drop_table('logmnr_dictstate$')
    op.drop_index(op.f('logmnr_i1attribute$'), table_name='logmnr_attribute$')
    op.drop_table('logmnr_attribute$')
    op.drop_index(op.f('logmnr_i1lob$'), table_name='logmnr_lob$')
    op.drop_table('logmnr_lob$')
    op.drop_index(op.f('logmnrc_i1user'), table_name='logmnrc_user')
    op.drop_table('logmnrc_user')
    op.drop_index(op.f('logmnr_i1obj$'), table_name='logmnr_obj$')
    op.drop_index(op.f('logmnr_i2obj$'), table_name='logmnr_obj$')
    op.drop_index(op.f('logmnr_i3obj$'), table_name='logmnr_obj$')
    op.drop_table('logmnr_obj$')
    op.drop_index(op.f('logmnr_i1subcoltype$'), table_name='logmnr_subcoltype$')
    op.drop_table('logmnr_subcoltype$')
    op.drop_index(op.f('logmnr_i1coltype$'), table_name='logmnr_coltype$')
    op.drop_table('logmnr_coltype$')
    op.drop_index(op.f('logmnrc_i1tspart'), table_name='logmnrc_tspart')
    op.drop_table('logmnrc_tspart')
    op.drop_index(op.f('logmnr_i1col$'), table_name='logmnr_col$')
    op.drop_index(op.f('logmnr_i2col$'), table_name='logmnr_col$')
    op.drop_index(op.f('logmnr_i3col$'), table_name='logmnr_col$')
    op.drop_table('logmnr_col$')
    op.drop_index(op.f('logmnr_i1indpart$'), table_name='logmnr_indpart$')
    op.drop_index(op.f('logmnr_i2indpart$'), table_name='logmnr_indpart$')
    op.drop_table('logmnr_indpart$')
    op.drop_index(op.f('logmnr_i1tabcompart$'), table_name='logmnr_tabcompart$')
    op.drop_index(op.f('logmnr_i2tabcompart$'), table_name='logmnr_tabcompart$')
    op.drop_table('logmnr_tabcompart$')
    op.drop_index(op.f('logmnrp_ctas_part_map_i'), table_name='logmnrp_ctas_part_map')
    op.drop_table('logmnrp_ctas_part_map')
    op.drop_index(op.f('logmnr_i1ntab$'), table_name='logmnr_ntab$')
    op.drop_index(op.f('logmnr_i2ntab$'), table_name='logmnr_ntab$')
    op.drop_table('logmnr_ntab$')
    op.drop_index(op.f('logmnr_i1ind$'), table_name='logmnr_ind$')
    op.drop_index(op.f('logmnr_i2ind$'), table_name='logmnr_ind$')
    op.drop_table('logmnr_ind$')
    op.drop_index(op.f('logmnr_i1type$'), table_name='logmnr_type$')
    op.drop_table('logmnr_type$')
    op.drop_index(op.f('logmnrc_i1shard_ts'), table_name='logmnrc_shard_ts')
    op.drop_table('logmnrc_shard_ts')
    op.drop_index(op.f('logmnr_i1tabsubpart$'), table_name='logmnr_tabsubpart$')
    op.drop_index(op.f('logmnr_i2tabsubpart$'), table_name='logmnr_tabsubpart$')
    op.drop_table('logmnr_tabsubpart$')
    op.drop_index(op.f('logmnr_i1indsubpart$'), table_name='logmnr_indsubpart$')
    op.drop_table('logmnr_indsubpart$')
    op.drop_index(op.f('logmnr_i1attrcol$'), table_name='logmnr_attrcol$')
    op.drop_table('logmnr_attrcol$')
    op.drop_index(op.f('logmnrc_i1congg'), table_name='logmnrc_con_gg')
    op.drop_index(op.f('logmnrc_i2congg'), table_name='logmnrc_con_gg')
    op.drop_table('logmnrc_con_gg')
    op.drop_index(op.f('logmnrc_i2gtcs'), table_name='logmnrc_gtcs')
    op.drop_table('logmnrc_gtcs')
    op.drop_index(op.f('logmnr_i1logmnr_buildlog'), table_name='logmnr_logmnr_buildlog')
    op.drop_table('logmnr_logmnr_buildlog')
    op.drop_index(op.f('logmnr_i1indcompart$'), table_name='logmnr_indcompart$')
    op.drop_table('logmnr_indcompart$')
    op.drop_index(op.f('logmnr_i1seed$'), table_name='logmnr_seed$')
    op.drop_index(op.f('logmnr_i2seed$'), table_name='logmnr_seed$')
    op.drop_table('logmnr_seed$')
    op.drop_table('logmnrc_indcol_gg')
    op.drop_index(op.f('logmnr_i1partobj$'), table_name='logmnr_partobj$')
    op.drop_table('logmnr_partobj$')
    op.drop_index(op.f('logmnr_i1tab$'), table_name='logmnr_tab$')
    op.drop_index(op.f('logmnr_i2tab$'), table_name='logmnr_tab$')
    op.drop_table('logmnr_tab$')
    op.drop_index(op.f('logmnr_i1icol$'), table_name='logmnr_icol$')
    op.drop_table('logmnr_icol$')
    op.drop_index(op.f('logmnrc_i2gtlo'), table_name='logmnrc_gtlo')
    op.drop_index(op.f('logmnrc_i3gtlo'), table_name='logmnrc_gtlo')
    op.drop_table('logmnrc_gtlo')
    op.drop_table('logmnrc_concol_gg')
    op.drop_index(op.f('logmnr_i1user$'), table_name='logmnr_user$')
    op.drop_index(op.f('logmnr_i2user$'), table_name='logmnr_user$')
    op.drop_table('logmnr_user$')
    op.drop_index(op.f('logmnr_i1dictionary$'), table_name='logmnr_dictionary$')
    op.drop_table('logmnr_dictionary$')
    op.drop_table('logstdby$apply_progress')
    op.drop_index(op.f('logmnr_i1container$'), table_name='logmnr_container$')
    op.drop_table('logmnr_container$')
    op.drop_index(op.f('logmnr_i1kopm$'), table_name='logmnr_kopm$')
    op.drop_table('logmnr_kopm$')
    op.drop_index(op.f('logmnr_i1tabpart$'), table_name='logmnr_tabpart$')
    op.drop_index(op.f('logmnr_i2tabpart$'), table_name='logmnr_tabpart$')
    op.drop_table('logmnr_tabpart$')
    op.drop_index(op.f('logmnr_i1con$'), table_name='logmnr_con$')
    op.drop_table('logmnr_con$')
    op.drop_index(op.f('logmnr_i1refcon$'), table_name='logmnr_refcon$')
    op.drop_table('logmnr_refcon$')
    op.drop_index(op.f('logmnr_i1ts$'), table_name='logmnr_ts$')
    op.drop_table('logmnr_ts$')
    op.drop_index(op.f('logmnr_i1ccol$'), table_name='logmnr_ccol$')
    op.drop_table('logmnr_ccol$')
    op.drop_index(op.f('logmnr_i1opqtype$'), table_name='logmnr_opqtype$')
    op.drop_table('logmnr_opqtype$')
    op.drop_index(op.f('logmnrc_i1ts'), table_name='logmnrc_ts')
    op.drop_table('logmnrc_ts')
    op.drop_index(op.f('logmnr_i1enc$'), table_name='logmnr_enc$')
    op.drop_table('logmnr_enc$')
    op.drop_index(op.f('logmnr_i1lobfrag$'), table_name='logmnr_lobfrag$')
    op.drop_table('logmnr_lobfrag$')
    op.drop_index(op.f('logmnr_i1props$'), table_name='logmnr_props$')
    op.drop_table('logmnr_props$')
    op.drop_index(op.f('logmnr_i1idnseq$'), table_name='logmnr_idnseq$')
    op.drop_index(op.f('logmnr_i2idnseq$'), table_name='logmnr_idnseq$')
    op.drop_table('logmnr_idnseq$')
    op.drop_table('logmnrc_gsba')
    op.drop_index(op.f('logmnr_i1shard_ts'), table_name='logmnr_shard_ts')
    op.drop_table('logmnr_shard_ts')
    op.drop_index(op.f('logmnrc_i1indgg'), table_name='logmnrc_ind_gg')
    op.drop_index(op.f('logmnrc_i2indgg'), table_name='logmnrc_ind_gg')
    op.drop_table('logmnrc_ind_gg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logmnrc_ind_gg',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=384), nullable=False),
    sa.Column('commit_scn', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('drop_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('BASEOBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('BASEOBJV#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('flags', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('OWNER#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('ownername', sa.VARCHAR(length=384), nullable=False),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare4', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('spare5', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('spare6', sa.VARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'commit_scn', name=op.f('logmnrc_ind_gg_pk'))
    )
    op.create_index(op.f('logmnrc_i2indgg'), 'logmnrc_ind_gg', ['logmnr_uid', 'drop_scn'], unique=False)
    op.create_index(op.f('logmnrc_i1indgg'), 'logmnrc_ind_gg', ['logmnr_uid', 'BASEOBJ#', 'BASEOBJV#', 'commit_scn'], unique=False)
    op.create_table('logmnr_shard_ts',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('tablespace_name', sa.VARCHAR(length=90), nullable=False),
    sa.Column('chunk_number', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('start_scnbas', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('start_scnwrp', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'tablespace_name', name=op.f('logmnr_shard_ts_pk'))
    )
    op.create_index(op.f('logmnr_i1shard_ts'), 'logmnr_shard_ts', ['logmnr_uid', 'tablespace_name'], unique=False)
    op.create_table('logmnrc_gsba',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('as_of_scn', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('fdo_length', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('fdo_value', oracle.RAW(), nullable=True),
    sa.Column('charsetid', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ncharsetid', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('dbtimezone_len', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('dbtimezone_value', sa.VARCHAR(length=192), nullable=True),
    sa.Column('logmnr_spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare3', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('logmnr_spare4', oracle.DATE(), nullable=True),
    sa.Column('db_global_name', sa.VARCHAR(length=384), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'as_of_scn', name=op.f('logmnrc_gsba_pk'))
    )
    op.create_table('logmnr_idnseq$',
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('SEQOBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('startwith', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'INTCOL#', name=op.f('logmnr_idnseq$_pk'))
    )
    op.create_index(op.f('logmnr_i2idnseq$'), 'logmnr_idnseq$', ['logmnr_uid', 'SEQOBJ#'], unique=False)
    op.create_index(op.f('logmnr_i1idnseq$'), 'logmnr_idnseq$', ['logmnr_uid', 'OBJ#', 'INTCOL#'], unique=False)
    op.create_table('logmnr_props$',
    sa.Column('value$', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('comment$', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('name', sa.VARCHAR(length=384), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'name', name=op.f('logmnr_props$_pk'))
    )
    op.create_index(op.f('logmnr_i1props$'), 'logmnr_props$', ['logmnr_uid', 'name'], unique=False)
    op.create_table('logmnr_lobfrag$',
    sa.Column('FRAGOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('PARENTOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('TABFRAGOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('INDFRAGOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('FRAG#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'FRAGOBJ#', name=op.f('logmnr_lobfrag$_pk'))
    )
    op.create_index(op.f('logmnr_i1lobfrag$'), 'logmnr_lobfrag$', ['logmnr_uid', 'FRAGOBJ#'], unique=False)
    op.create_table('logmnr_enc$',
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('OWNER#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('encalg', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('intalg', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('colklc', oracle.RAW(), nullable=True),
    sa.Column('klclen', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('flag', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('mkeyid', sa.VARCHAR(length=192), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'OWNER#', name=op.f('logmnr_enc$_pk'))
    )
    op.create_index(op.f('logmnr_i1enc$'), 'logmnr_enc$', ['logmnr_uid', 'OBJ#', 'OWNER#'], unique=False)
    op.create_table('logmnrc_ts',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('TS#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=90), nullable=True),
    sa.Column('start_scn', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('drop_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'TS#', 'start_scn', name=op.f('logmnrc_ts_pk'))
    )
    op.create_index(op.f('logmnrc_i1ts'), 'logmnrc_ts', ['logmnr_uid', 'drop_scn'], unique=False)
    op.create_table('logmnr_opqtype$',
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('type', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('flags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('lobcol', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('objcol', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('extracol', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('schemaoid', oracle.RAW(), nullable=True),
    sa.Column('elemnum', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('schemaurl', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'INTCOL#', name=op.f('logmnr_opqtype$_pk'))
    )
    op.create_index(op.f('logmnr_i1opqtype$'), 'logmnr_opqtype$', ['logmnr_uid', 'OBJ#', 'INTCOL#'], unique=False)
    op.create_table('logmnr_ccol$',
    sa.Column('CON#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('COL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('POS#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'CON#', 'INTCOL#', name=op.f('logmnr_ccol$_pk'))
    )
    op.create_index(op.f('logmnr_i1ccol$'), 'logmnr_ccol$', ['logmnr_uid', 'CON#', 'INTCOL#'], unique=False)
    op.create_table('logmnr_ts$',
    sa.Column('TS#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('name', sa.VARCHAR(length=90), nullable=True),
    sa.Column('OWNER#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('blocksize', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('start_scnbas', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('start_scnwrp', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'TS#', name=op.f('logmnr_ts$_pk'))
    )
    op.create_index(op.f('logmnr_i1ts$'), 'logmnr_ts$', ['logmnr_uid', 'TS#'], unique=False)
    op.create_table('logmnr_refcon$',
    sa.Column('COL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('reftyp', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('stabid', oracle.RAW(), nullable=True),
    sa.Column('expctoid', oracle.RAW(), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'INTCOL#', name=op.f('logmnr_refcon$_pk'))
    )
    op.create_index(op.f('logmnr_i1refcon$'), 'logmnr_refcon$', ['logmnr_uid', 'OBJ#', 'INTCOL#'], unique=False)
    op.create_table('logmnr_con$',
    sa.Column('OWNER#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=384), nullable=False),
    sa.Column('CON#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('start_scnbas', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('start_scnwrp', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'CON#', name=op.f('logmnr_con$_pk'))
    )
    op.create_index(op.f('logmnr_i1con$'), 'logmnr_con$', ['logmnr_uid', 'CON#'], unique=False)
    op.create_table('logmnr_tabpart$',
    sa.Column('OBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('TS#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('PART#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('BO#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'BO#', name=op.f('logmnr_tabpart$_pk'))
    )
    op.create_index(op.f('logmnr_i2tabpart$'), 'logmnr_tabpart$', ['logmnr_uid', 'BO#'], unique=False)
    op.create_index(op.f('logmnr_i1tabpart$'), 'logmnr_tabpart$', ['logmnr_uid', 'OBJ#', 'BO#'], unique=False)
    op.create_table('logmnr_kopm$',
    sa.Column('length', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('metadata', oracle.RAW(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=384), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'name', name=op.f('logmnr_kopm$_pk'))
    )
    op.create_index(op.f('logmnr_i1kopm$'), 'logmnr_kopm$', ['logmnr_uid', 'name'], unique=False)
    op.create_table('logmnr_container$',
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('CON_ID#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('dbid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('con_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('create_scnwrp', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('create_scnbas', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('flags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('status', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('vsn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('FED_ROOT_CON_ID#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', name=op.f('logmnr_container$_pk'))
    )
    op.create_index(op.f('logmnr_i1container$'), 'logmnr_container$', ['logmnr_uid', 'CON_ID#'], unique=False)
    op.create_table('logstdby$apply_progress',
    sa.Column('xidusn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xidslt', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xidsqn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('commit_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('commit_time', oracle.DATE(), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=2000), nullable=True)
    )
    op.create_table('logmnr_dictionary$',
    sa.Column('db_name', sa.VARCHAR(length=27), nullable=True),
    sa.Column('db_id', oracle.NUMBER(precision=20, scale=0, asdecimal=False), nullable=True),
    sa.Column('db_created', sa.VARCHAR(length=20), nullable=True),
    sa.Column('db_dict_created', sa.VARCHAR(length=20), nullable=True),
    sa.Column('db_dict_scn', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('db_thread_map', oracle.RAW(), nullable=True),
    sa.Column('db_txn_scnbas', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('db_txn_scnwrp', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('DB_RESETLOGS_CHANGE#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('db_resetlogs_time', sa.VARCHAR(length=20), nullable=True),
    sa.Column('db_version_time', sa.VARCHAR(length=20), nullable=True),
    sa.Column('db_redo_type_id', sa.VARCHAR(length=8), nullable=True),
    sa.Column('db_redo_release', sa.VARCHAR(length=60), nullable=True),
    sa.Column('db_character_set', sa.VARCHAR(length=192), nullable=True),
    sa.Column('db_version', sa.VARCHAR(length=240), nullable=True),
    sa.Column('db_status', sa.VARCHAR(length=240), nullable=True),
    sa.Column('db_global_name', sa.VARCHAR(length=384), nullable=True),
    sa.Column('db_dict_maxobjects', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('db_dict_objectcount', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('pdb_name', sa.VARCHAR(length=384), nullable=True),
    sa.Column('pdb_id', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('pdb_uid', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('pdb_dbid', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('pdb_guid', oracle.RAW(), nullable=True),
    sa.Column('pdb_create_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('pdb_count', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('pdb_global_name', sa.VARCHAR(length=384), nullable=True),
    sa.Column('FED_ROOT_CON_ID#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', name=op.f('logmnr_dictionary$_pk'))
    )
    op.create_index(op.f('logmnr_i1dictionary$'), 'logmnr_dictionary$', ['logmnr_uid'], unique=False)
    op.create_table('logmnr_user$',
    sa.Column('USER#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('name', sa.VARCHAR(length=384), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'USER#', name=op.f('logmnr_user$_pk'))
    )
    op.create_index(op.f('logmnr_i2user$'), 'logmnr_user$', ['logmnr_uid', 'name'], unique=False)
    op.create_index(op.f('logmnr_i1user$'), 'logmnr_user$', ['logmnr_uid', 'USER#'], unique=False)
    op.create_table('logmnrc_concol_gg',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('CON#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('commit_scn', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('POS#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'CON#', 'commit_scn', 'INTCOL#', name=op.f('logmnrc_concol_gg_pk'))
    )
    op.create_table('logmnrc_gtlo',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('KEYOBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('lvlcnt', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('BASEOBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('BASEOBJV#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('LVL1OBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('LVL2OBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('LVL0TYPE#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('LVL1TYPE#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('LVL2TYPE#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('OWNER#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ownername', sa.VARCHAR(length=384), nullable=False),
    sa.Column('lvl0name', sa.VARCHAR(length=384), nullable=False),
    sa.Column('lvl1name', sa.VARCHAR(length=384), nullable=True),
    sa.Column('lvl2name', sa.VARCHAR(length=384), nullable=True),
    sa.Column('intcols', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('cols', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('kernelcols', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('tab_flags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('trigflag', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ASSOC#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('obj_flags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('TS#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('tsname', sa.VARCHAR(length=90), nullable=True),
    sa.Column('property', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('start_scn', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('drop_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xidusn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xidslt', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xidsqn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('flags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare3', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('logmnr_spare4', oracle.DATE(), nullable=True),
    sa.Column('logmnr_spare5', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare6', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare7', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare8', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare9', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('parttype', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('subparttype', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('unsupportedcols', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('complextypecols', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ntparentobjnum', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ntparentobjversion', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ntparentintcolnum', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnrtloflags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnrmcv', sa.VARCHAR(length=30), nullable=True),
    sa.Column('acdrflags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ACDRTSOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ACDRROWTSINTCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'KEYOBJ#', 'BASEOBJV#', name=op.f('logmnrc_gtlo_pk'))
    )
    op.create_index(op.f('logmnrc_i3gtlo'), 'logmnrc_gtlo', ['logmnr_uid', 'drop_scn'], unique=False)
    op.create_index(op.f('logmnrc_i2gtlo'), 'logmnrc_gtlo', ['logmnr_uid', 'BASEOBJ#', 'BASEOBJV#'], unique=False)
    op.create_table('logmnr_icol$',
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('BO#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('COL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('POS#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('SEGCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'INTCOL#', name=op.f('logmnr_icol$_pk'))
    )
    op.create_index(op.f('logmnr_i1icol$'), 'logmnr_icol$', ['logmnr_uid', 'OBJ#', 'INTCOL#'], unique=False)
    op.create_table('logmnr_tab$',
    sa.Column('TS#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('cols', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('property', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('intcols', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('kernelcols', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('BOBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('trigflag', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('acdrflags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ACDRTSOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ACDRROWTSINTCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', name=op.f('logmnr_tab$_pk'))
    )
    op.create_index(op.f('logmnr_i2tab$'), 'logmnr_tab$', ['logmnr_uid', 'BOBJ#'], unique=False)
    op.create_index(op.f('logmnr_i1tab$'), 'logmnr_tab$', ['logmnr_uid', 'OBJ#'], unique=False)
    op.create_table('logmnr_partobj$',
    sa.Column('parttype', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('partcnt', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('partkeycols', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('flags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('DEFTS#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('defpctfree', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('defpctused', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('defpctthres', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('definitrans', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('defmaxtrans', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('deftiniexts', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('defextsize', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('defminexts', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('defmaxexts', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('defextpct', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('deflists', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('defgroups', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('deflogging', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('definclcol', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('parameters', sa.VARCHAR(length=3000), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', name=op.f('logmnr_partobj$_pk'))
    )
    op.create_index(op.f('logmnr_i1partobj$'), 'logmnr_partobj$', ['logmnr_uid', 'OBJ#'], unique=False)
    op.create_table('logmnrc_indcol_gg',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('commit_scn', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('POS#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'commit_scn', 'INTCOL#', name=op.f('logmnrc_indcol_gg_pk'))
    )
    op.create_table('logmnr_seed$',
    sa.Column('seed_version', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('gather_version', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('schemaname', sa.VARCHAR(length=384), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('OBJV#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('table_name', sa.VARCHAR(length=384), nullable=True),
    sa.Column('col_name', sa.VARCHAR(length=384), nullable=True),
    sa.Column('COL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('SEGCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('TYPE#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('length', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('PRECISION#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('scale', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('null$', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'INTCOL#', name=op.f('logmnr_seed$_pk'))
    )
    op.create_index(op.f('logmnr_i2seed$'), 'logmnr_seed$', ['logmnr_uid', 'schemaname', 'table_name', 'col_name', 'OBJ#', 'INTCOL#'], unique=False)
    op.create_index(op.f('logmnr_i1seed$'), 'logmnr_seed$', ['logmnr_uid', 'OBJ#', 'INTCOL#'], unique=False)
    op.create_table('logmnr_indcompart$',
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('DATAOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('BO#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('PART#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', name=op.f('logmnr_indcompart$_pk'))
    )
    op.create_index(op.f('logmnr_i1indcompart$'), 'logmnr_indcompart$', ['logmnr_uid', 'OBJ#'], unique=False)
    op.create_table('logmnr_logmnr_buildlog',
    sa.Column('build_date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('db_txn_scnbas', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('db_txn_scnwrp', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('current_build_state', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('completion_status', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('marked_log_file_low_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('initial_xid', sa.VARCHAR(length=22), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('cdb_xid', sa.VARCHAR(length=22), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', sa.VARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'initial_xid', name=op.f('logmnr_logmnr_buildlog_pk'))
    )
    op.create_index(op.f('logmnr_i1logmnr_buildlog'), 'logmnr_logmnr_buildlog', ['logmnr_uid', 'initial_xid'], unique=False)
    op.create_table('logmnrc_gtcs',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('OBJV#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('SEGCOL#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('colname', sa.VARCHAR(length=384), nullable=False),
    sa.Column('TYPE#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('length', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('scale', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('interval_leading_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('interval_trailing_precision', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('property', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('toid', oracle.RAW(), nullable=True),
    sa.Column('charsetid', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('charsetform', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('typename', sa.VARCHAR(length=384), nullable=True),
    sa.Column('fqcolname', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('numintcols', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('numattrs', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('adtorder', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare3', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('logmnr_spare4', oracle.DATE(), nullable=True),
    sa.Column('logmnr_spare5', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare6', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare7', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare8', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare9', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('COL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xtypeschemaname', sa.VARCHAR(length=384), nullable=True),
    sa.Column('xtypename', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('xfqcolname', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('xtopintcol', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xreffedtableobjn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xreffedtableobjv', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xcoltypeflags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xopqtypetype', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xopqtypeflags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xopqlobintcol', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xopqobjintcol', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('xxmlintcol', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('EAOWNER#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('eamkeyid', sa.VARCHAR(length=192), nullable=True),
    sa.Column('eaencalg', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('eaintalg', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('eacolklc', oracle.RAW(), nullable=True),
    sa.Column('eaklclen', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('eaflags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnrderivedflags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('collid', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('COLLINTCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ACDRRESCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'OBJV#', 'INTCOL#', name=op.f('logmnrc_gtcs_pk'))
    )
    op.create_index(op.f('logmnrc_i2gtcs'), 'logmnrc_gtcs', ['logmnr_uid', 'OBJ#', 'OBJV#', 'SEGCOL#', 'INTCOL#'], unique=False)
    op.create_table('logmnrc_con_gg',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('CON#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('name', sa.VARCHAR(length=384), nullable=False),
    sa.Column('commit_scn', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('drop_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('BASEOBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('BASEOBJV#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('flags', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('INDEXOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare4', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('spare5', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('spare6', sa.VARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'CON#', 'commit_scn', name=op.f('logmnrc_con_gg_pk'))
    )
    op.create_index(op.f('logmnrc_i2congg'), 'logmnrc_con_gg', ['logmnr_uid', 'drop_scn'], unique=False)
    op.create_index(op.f('logmnrc_i1congg'), 'logmnrc_con_gg', ['logmnr_uid', 'BASEOBJ#', 'BASEOBJV#', 'commit_scn'], unique=False)
    op.create_table('logmnr_attrcol$',
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('name', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'INTCOL#', name=op.f('logmnr_attrcol$_pk'))
    )
    op.create_index(op.f('logmnr_i1attrcol$'), 'logmnr_attrcol$', ['logmnr_uid', 'OBJ#', 'INTCOL#'], unique=False)
    op.create_table('logmnr_indsubpart$',
    sa.Column('OBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('DATAOBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('POBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('SUBPART#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('TS#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'POBJ#', name=op.f('logmnr_indsubpart$_pk'))
    )
    op.create_index(op.f('logmnr_i1indsubpart$'), 'logmnr_indsubpart$', ['logmnr_uid', 'OBJ#', 'POBJ#'], unique=False)
    op.create_table('logmnr_tabsubpart$',
    sa.Column('OBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('DATAOBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('POBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('SUBPART#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('TS#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'POBJ#', name=op.f('logmnr_tabsubpart$_pk'))
    )
    op.create_index(op.f('logmnr_i2tabsubpart$'), 'logmnr_tabsubpart$', ['logmnr_uid', 'POBJ#'], unique=False)
    op.create_index(op.f('logmnr_i1tabsubpart$'), 'logmnr_tabsubpart$', ['logmnr_uid', 'OBJ#', 'POBJ#'], unique=False)
    op.create_table('logmnrc_shard_ts',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('tablespace_name', sa.VARCHAR(length=90), nullable=False),
    sa.Column('chunk_number', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('start_scn', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('drop_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'tablespace_name', 'start_scn', name=op.f('logmnrc_shard_ts_pk'))
    )
    op.create_index(op.f('logmnrc_i1shard_ts'), 'logmnrc_shard_ts', ['logmnr_uid', 'drop_scn'], unique=False)
    op.create_table('logmnr_type$',
    sa.Column('VERSION#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('version', sa.VARCHAR(length=384), nullable=True),
    sa.Column('tvoid', oracle.RAW(), nullable=True),
    sa.Column('typecode', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('properties', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('attributes', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('methods', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('hiddenmethods', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('supertypes', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('subtypes', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('externtype', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('externname', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('helperclassname', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('local_attrs', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('local_methods', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('typeid', oracle.RAW(), nullable=True),
    sa.Column('roottoid', oracle.RAW(), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('supertoid', oracle.RAW(), nullable=True),
    sa.Column('hashcode', oracle.RAW(), nullable=True),
    sa.Column('toid', oracle.RAW(), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'toid', 'VERSION#', name=op.f('logmnr_type$_pk'))
    )
    op.create_index(op.f('logmnr_i1type$'), 'logmnr_type$', ['logmnr_uid', 'toid', 'VERSION#'], unique=False)
    op.create_table('logmnr_ind$',
    sa.Column('BO#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('cols', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('TYPE#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('flags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('property', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', name=op.f('logmnr_ind$_pk'))
    )
    op.create_index(op.f('logmnr_i2ind$'), 'logmnr_ind$', ['logmnr_uid', 'BO#'], unique=False)
    op.create_index(op.f('logmnr_i1ind$'), 'logmnr_ind$', ['logmnr_uid', 'OBJ#'], unique=False)
    op.create_table('logmnr_ntab$',
    sa.Column('COL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('NTAB#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('name', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'INTCOL#', name=op.f('logmnr_ntab$_pk'))
    )
    op.create_index(op.f('logmnr_i2ntab$'), 'logmnr_ntab$', ['logmnr_uid', 'NTAB#'], unique=False)
    op.create_index(op.f('logmnr_i1ntab$'), 'logmnr_ntab$', ['logmnr_uid', 'OBJ#', 'INTCOL#'], unique=False)
    op.create_table('logmnrp_ctas_part_map',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('BASEOBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('BASEOBJV#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('KEYOBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('PART#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'BASEOBJV#', 'KEYOBJ#', name=op.f('logmnrp_ctas_part_map_pk'))
    )
    op.create_index(op.f('logmnrp_ctas_part_map_i'), 'logmnrp_ctas_part_map', ['logmnr_uid', 'BASEOBJ#', 'BASEOBJV#', 'PART#'], unique=False)
    op.create_table('logmnr_tabcompart$',
    sa.Column('OBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('BO#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('PART#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', name=op.f('logmnr_tabcompart$_pk'))
    )
    op.create_index(op.f('logmnr_i2tabcompart$'), 'logmnr_tabcompart$', ['logmnr_uid', 'BO#'], unique=False)
    op.create_index(op.f('logmnr_i1tabcompart$'), 'logmnr_tabcompart$', ['logmnr_uid', 'OBJ#'], unique=False)
    op.create_table('logmnr_indpart$',
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('BO#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('PART#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('TS#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'BO#', name=op.f('logmnr_indpart$_pk'))
    )
    op.create_index(op.f('logmnr_i2indpart$'), 'logmnr_indpart$', ['logmnr_uid', 'BO#'], unique=False)
    op.create_index(op.f('logmnr_i1indpart$'), 'logmnr_indpart$', ['logmnr_uid', 'OBJ#', 'BO#'], unique=False)
    op.create_table('logmnr_col$',
    sa.Column('COL#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('SEGCOL#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('name', sa.VARCHAR(length=384), nullable=True),
    sa.Column('TYPE#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('length', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('PRECISION#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('scale', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('null$', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('INTCOL#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('property', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('charsetid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('charsetform', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('spare1', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('collid', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('COLLINTCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ACDRRESCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'INTCOL#', name=op.f('logmnr_col$_pk'))
    )
    op.create_index(op.f('logmnr_i3col$'), 'logmnr_col$', ['logmnr_uid', 'OBJ#', 'COL#'], unique=False)
    op.create_index(op.f('logmnr_i2col$'), 'logmnr_col$', ['logmnr_uid', 'OBJ#', 'name'], unique=False)
    op.create_index(op.f('logmnr_i1col$'), 'logmnr_col$', ['logmnr_uid', 'OBJ#', 'INTCOL#'], unique=False)
    op.create_table('logmnrc_tspart',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('TS#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('start_scn', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('drop_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'start_scn', name=op.f('logmnrc_tspart_pk'))
    )
    op.create_index(op.f('logmnrc_i1tspart'), 'logmnrc_tspart', ['logmnr_uid', 'drop_scn'], unique=False)
    op.create_table('logmnr_coltype$',
    sa.Column('COL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('toid', oracle.RAW(), nullable=True),
    sa.Column('VERSION#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('packed', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('intcols', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('INTCOL#S', oracle.RAW(), nullable=True),
    sa.Column('flags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('TYPIDCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('SYNOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'INTCOL#', name=op.f('logmnr_coltype$_pk'))
    )
    op.create_index(op.f('logmnr_i1coltype$'), 'logmnr_coltype$', ['logmnr_uid', 'OBJ#', 'INTCOL#'], unique=False)
    op.create_table('logmnr_subcoltype$',
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('toid', oracle.RAW(), nullable=False),
    sa.Column('VERSION#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('intcols', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('INTCOL#S', oracle.RAW(), nullable=True),
    sa.Column('flags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('SYNOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'INTCOL#', 'toid', name=op.f('logmnr_subcoltype$_pk'))
    )
    op.create_index(op.f('logmnr_i1subcoltype$'), 'logmnr_subcoltype$', ['logmnr_uid', 'OBJ#', 'INTCOL#', 'toid'], unique=False)
    op.create_table('logmnr_obj$',
    sa.Column('OBJV#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('OWNER#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('name', sa.VARCHAR(length=384), nullable=True),
    sa.Column('namespace', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('subname', sa.VARCHAR(length=384), nullable=True),
    sa.Column('TYPE#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('oid$', oracle.RAW(), nullable=True),
    sa.Column('remoteowner', sa.VARCHAR(length=384), nullable=True),
    sa.Column('linkname', sa.VARCHAR(length=384), nullable=True),
    sa.Column('flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('spare3', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('stime', oracle.DATE(), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('start_scnbas', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('start_scnwrp', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', name=op.f('logmnr_obj$_pk'))
    )
    op.create_index(op.f('logmnr_i3obj$'), 'logmnr_obj$', ['logmnr_uid', 'name'], unique=False)
    op.create_index(op.f('logmnr_i2obj$'), 'logmnr_obj$', ['logmnr_uid', 'oid$'], unique=False)
    op.create_index(op.f('logmnr_i1obj$'), 'logmnr_obj$', ['logmnr_uid', 'OBJ#'], unique=False)
    op.create_table('logmnrc_user',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('USER#', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=False),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('name', sa.VARCHAR(length=384), nullable=False),
    sa.Column('start_scn', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('drop_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare1_c', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2_c', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3_c', sa.VARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'USER#', 'start_scn', name=op.f('logmnrc_user_pk'))
    )
    op.create_index(op.f('logmnrc_i1user'), 'logmnrc_user', ['logmnr_uid', 'name', 'start_scn'], unique=False)
    op.create_table('logmnr_lob$',
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('INTCOL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('COL#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('LOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('chunk', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'INTCOL#', name=op.f('logmnr_lob$_pk'))
    )
    op.create_index(op.f('logmnr_i1lob$'), 'logmnr_lob$', ['logmnr_uid', 'OBJ#', 'INTCOL#'], unique=False)
    op.create_table('logmnr_attribute$',
    sa.Column('VERSION#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('name', sa.VARCHAR(length=384), nullable=True),
    sa.Column('ATTRIBUTE#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('attr_toid', oracle.RAW(), nullable=True),
    sa.Column('ATTR_VERSION#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('SYNOBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('properties', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('charsetid', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('charsetform', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('length', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('PRECISION#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('scale', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('externname', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('xflags', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare4', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare5', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('setter', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('getter', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('toid', oracle.RAW(), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'toid', 'VERSION#', 'ATTRIBUTE#', name=op.f('logmnr_attribute$_pk'))
    )
    op.create_index(op.f('logmnr_i1attribute$'), 'logmnr_attribute$', ['logmnr_uid', 'toid', 'VERSION#', 'ATTRIBUTE#'], unique=False)
    op.create_table('logmnr_dictstate$',
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('start_scnbas', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('start_scnwrp', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('end_scnbas', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('end_scnwrp', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('redo_thread', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('rbasqn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('rbablk', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('rbabyte', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', name=op.f('logmnr_dictstate$_pk'))
    )
    op.create_table('logmnrc_gsii',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('BO#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('INDTYPE#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('drop_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('logmnr_spare3', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('logmnr_spare4', oracle.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', name=op.f('logmnrc_gsii_pk'))
    )
    op.create_table('logmnrc_seq_gg',
    sa.Column('logmnr_uid', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('commit_scn', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('drop_scn', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('seq_flags', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('OWNER#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('ownername', sa.VARCHAR(length=384), nullable=False),
    sa.Column('objname', sa.VARCHAR(length=384), nullable=False),
    sa.Column('seqcache', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('seqinc', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare1', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare2', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('spare3', sa.VARCHAR(length=4000), nullable=True),
    sa.Column('spare4', sa.VARCHAR(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'OBJ#', 'commit_scn', name=op.f('logmnrc_seq_gg_pk'))
    )
    op.create_index(op.f('logmnrc_i2seqgg'), 'logmnrc_seq_gg', ['logmnr_uid', 'drop_scn'], unique=False)
    op.create_table('logmnr_cdef$',
    sa.Column('CON#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('cols', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('TYPE#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('ROBJ#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('RCON#', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('enabled', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('defer', oracle.NUMBER(asdecimal=False), nullable=True),
    sa.Column('OBJ#', oracle.NUMBER(asdecimal=False), nullable=False),
    sa.Column('logmnr_uid', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.Column('logmnr_flags', oracle.NUMBER(precision=22, scale=0, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('logmnr_uid', 'CON#', name=op.f('logmnr_cdef$_pk'))
    )
    op.create_index(op.f('logmnr_i3cdef$'), 'logmnr_cdef$', ['logmnr_uid', 'OBJ#'], unique=False)
    op.create_index(op.f('logmnr_i2cdef$'), 'logmnr_cdef$', ['logmnr_uid', 'ROBJ#'], unique=False)
    op.create_index(op.f('logmnr_i1cdef$'), 'logmnr_cdef$', ['logmnr_uid', 'CON#'], unique=False)
    op.drop_table('pagos')
    op.drop_index(op.f('ix_facturas_num_factura'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_table('clientes')
    op.drop_table('tipo_clientes')
    op.drop_table('productos')
    op.drop_table('categoria_productos')
    op.drop_table('cartera')
    # ### end Alembic commands ###
